### ISSUE TITLE
Interpolation doesn't work?

### ISSUE THREAD

**Issue by TheHyper-Dev** [Colanderp/UnityTutorials#1]
The camera movement is fine but the controller movement is still laggy. Can you please help?
I'm using the latest Unity LTS version (2018.4)

**Comment by nseam** [comment]
I'm also having such a laggy interpolation. I'm using Unity 2019.3.7f1.

**Comment by Colanderp** [comment]
Do both of you have the interpolation controller prefab in the scene?

**Comment by TheHyper-Dev** [comment]
Another script was cancelling the interpolation prefabs, it works now. Thanks

**Comment by nseam** [comment]
I am now using other type of FPS controller, but I will test your one again tomorrow, maybe it will be better without interpolation issues

**Comment by nseam** [comment]
@W4R-The-Hyper Could you tell us how you fixed the interpolation problem? Which script cancelled or deny interpolating?

**Comment by TheHyper-Dev** [comment]
It's a script of mine, long story :p

**Comment by Colanderp** [comment]
A good note that now PlayerMovement is a child of InterpolationTransform and so you should not have both PlayerMovement and InterpolationTransform on the same transform like you did before

**Comment by nseam** [comment]
@Colanderp Hi! I've created new Unity project, downloaded master branch, imported `FPS Movement Only.unitypackage`, then moved `Player` prefab onto the scene, and camera is still jerky.

Here is an Unity project you can check it out:

https://cloud.warp.sh/index.php/s/Ld2MittgHB8mb26

Here is a video of the issue:

`.MOV`: https://cloud.warp.sh/index.php/s/Tx8mjKdAbdkdy2n
`.MKV`: https://cloud.warp.sh/index.php/s/E2jkt9yGCEdBGBM

I'm experiencing problems with my current FPS controller so will be more than happy to be able to use your one, as it works ok. The only issue is camera lagging.

Note that I'm using Unity 2019.3.7f1.

Thank you for your help!

**Comment by Colanderp** [comment]
Did you place the InterpolationController prefab in the scene too?

**Comment by nseam** [comment]
Holy moly. I thought the Player prefab already contained all required components. After adding `InterpolationController` component into the `Player` object it just starter working okay.

Would be nice to include such information inside `README.md`. Maybe it is included in tutorial video, but I wasn't so much patient to watch it fully.

Thank you for helping me!

Have a nice day!

**Comment by Colanderp** [comment]
There ya go! Each has a README that explains that you need the InterpolationController.prefab
