### ISSUE TITLE
Objects shaking

### ISSUE THREAD

**Issue by m7d2** [Colanderp/UnityTutorials#2]
so i saw the YouTube videos about the advanced fps movement and i wanted to try them out. when i opened the project the objects start shaking i don't know why this is happening and how to fix it. Here is a video so you can see exactly what is the problem [Video](https://youtu.be/AzDCRuV3k38)

**Comment by fosterushka** [comment]
Hello there, you should add InterpolationPrefab into you scene.
Enjoy !
