### ISSUE TITLE
Missing LICENSE

### ISSUE THREAD

**Issue by TechnologyClassroom** [Colanderp/UnityTutorials#3]
I saw you gave this code the CC0 license on reddit: https://old.reddit.com/r/Unity3D/comments/gbwya1/i_worked_a_lot_on_this_while_in_quarantine_and_in/

You should make a LICENSE file in this repo that indicates that.  Would you like me to make a PR for that?

**Comment by Colanderp** [comment]
Honestly would love that haha. You are correct that it really should be in here

**Comment by Colanderp** [comment]
I think I got it! Let me know if that is better!
