### ISSUE TITLE
InverseKinematics type isn't found when importing "FPS Shooter.unitypackage"

### ISSUE THREAD

**Issue by rstecca** [Colanderp/UnityTutorials#5]
`Assets\_FPS Shooting\Scripts\ArmIKController.cs(14,12): error CS0246: The type or namespace name 'InverseKinematics' could not be found (are you missing a using directive or an assembly reference?)`

**Comment by jinincarnate** [comment]
You would need the Inverse Kinematics package(its free) from asset store, He explained all prerequisites in the video(such as installing blender,script execution order, creating layers before importing package) , do take a look.

**Comment by Colanderp** [comment]
> You would need the Inverse Kinematics package(its free) from asset store, He explained all prerequisites in the video(such as installing blender,script execution order, creating layers before importing package) , do take a look.

This is correct! Thank you jinincarnate! [Here is the video link](https://www.youtube.com/watch?v=HFvMxmn9cfQ)
